apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80          # External port
      targetPort: 3002  # Internal container port
  type: ClusterIP 