apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80          # External port
      targetPort: 3003  # Internal container port
  type: ClusterIP 